# Generated by Django 3.2.3 on 2022-01-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Path', models.CharField(max_length=100)),
            ],
        ),
    ]
