# Generated by Django 3.2.3 on 2022-03-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credentials',
            table='credentials',
        ),
    ]
