# Generated by Django 3.2.3 on 2021-06-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
